import { DEFAULT_ROLE_INFO } from '@/constant';

export const initUser = {
  admin1: {
    id: 1,
    username: 'admin1',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.SUPER_ADMIN.id],
  },
  admin2: {
    id: 2,
    username: 'admin2',
    password: '123456',
    user_roles: [DEFAULT_ROLE_INFO.SUPER_ADMIN.id],
    avatar: '',
  },
  admin3: {
    id: 3,
    username: 'admin3',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.SUPER_ADMIN.id],
  },
  vip_user1: {
    id: 4,
    username: 'vip_user1',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.VIP_USER.id],
  },
  vip_user2: {
    id: 5,
    username: 'vip_user2',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.VIP_USER.id],
  },
  vip_user3: {
    id: 6,
    username: 'vip_user3',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.VIP_USER.id],
  },
  svip_user1: {
    id: 7,
    username: 'svip_user1',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.SVIP_USER.id],
  },
  svip_user2: {
    id: 8,
    username: 'svip_user2',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.SVIP_USER.id],
  },
  svip_user3: {
    id: 9,
    username: 'svip_user3',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.SVIP_USER.id],
  },
  tourist1: {
    id: 10,
    username: 'tourist1',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.TOURIST_USER.id],
  },
  tourist2: {
    id: 11,
    username: 'tourist2',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.TOURIST_USER.id],
  },
  tourist3: {
    id: 12,
    username: 'tourist3',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.TOURIST_USER.id],
  },
  user_9999: {
    id: 9999,
    username: 'user_9999',
    password: '123456',
    avatar: '',
    user_roles: [DEFAULT_ROLE_INFO.VIP_USER.id],
  },
};
